/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shang_bspatchhotfix_bspatch_BsPatch */

#ifndef _Included_com_shang_bspatchhotfix_bspatch_BsPatch
#define _Included_com_shang_bspatchhotfix_bspatch_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shang_bspatchhotfix_bspatch_BsPatch
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_shang_bspatchhotfix_bspatch_BsPatch_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
